Week-4-Lab/calculatorApp/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/calculate", to: "calculator#calculate"
  post "/calculate", to: "calculator#calculate"
  post "/sum", to: "calculator#sum"
  post "/subtract", to: "calculator#subtract"
  post "/multiply", to: "calculator#multiply"
  post "/divide", to: "calculator#divide"
end

Week-4-Lab/calculatorApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Week-4-Lab/calculatorApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Week-4-Lab/calculatorApp/app/controllers/calculator_controller.rb
require 'arithmetic_calculator'

class CalculatorController < ApplicationController
    def calculate
    end

    def sum
        @num1 = params[:number1]
        @num2 = params[:number2]
        @result = ArithmeticCalculator.add(@num1.to_i, @num2.to_i)
        @operator_symbol = "+"
    end

    def subtract
        @num1 = params[:number1]
        @num2 = params[:number2]
        @result = ArithmeticCalculator.subtract(@num1.to_i, @num2.to_i)
        @operator_symbol = "-"
    end

    def multiply
        @num1 = params[:number1]
        @num2 = params[:number2]
        @result = ArithmeticCalculator.multiply(@num1.to_i, @num2.to_i)
        @operator_symbol = "*"
    end

    def divide
        @num1 = params[:number1]
        @num2 = params[:number2]
        @result = ArithmeticCalculator.divide(@num1.to_i, @num2.to_i)
        @operator_symbol = "/"
    end
    
end

Week-4-Lab/calculatorApp/app/helpers/application_helper.rb
module ApplicationHelper
end

Week-4-Lab/calculatorApp/app/helpers/calculator_helper.rb
module CalculatorHelper
end

Week-4-Lab/calculatorApp/app/views/calculator/calculate.html.erb
<h1>Simple Calculator</h1>

<%= form_with url: "/sum", local: true, data: { turbo: false } do |f| %>
  <%= text_field_tag :number1 %>
  <%= text_field_tag :number2 %>
  <%= submit_tag "+" %>
<% end %>

<br>

<%= form_with url: "/subtract", local: true, data: { turbo: false } do |f| %>
  <%= text_field_tag :number1 %>
  <%= text_field_tag :number2 %>
  <%= submit_tag "-" %>
<% end %>
<br>

<%= form_with url: "/multiply", local: true, data: { turbo: false } do |f| %>
  <%= text_field_tag :number1 %>
  <%= text_field_tag :number2 %>
  <%= submit_tag "*" %>
<% end %>
<br>

<%= form_with url: "/divide", local: true, data: { turbo: false } do |f| %>
  <%= text_field_tag :number1 %>
  <%= text_field_tag :number2 %>
  <%= submit_tag "/" %>
<% end %>

<hr>

<h1>Result</h1>
<br>

<% if @result %>
  <%= @num1 %> <%= operator_symbol %> <%= @num2 %> = <%= @result %>
<% end %>

Week-4-Lab/calculatorApp/app/views/calculator/divide.html.erb
<%= link_to 'Back to Full Calculator', calculate_path, class: "link-style" %>

<h1>Simple Calculator</h1>
<h3>Divide</h3>

<%= form_with url: "/divide", local: true, data: { turbo: false } do |f| %>
  <%= text_field_tag :number1 %>
  <%= text_field_tag :number2 %>
  <%= submit_tag "/" %>
<% end %>

<hr>

<h1>Divide</h1>
<br>
<%= @num1 %> / <%= @num2 %> = <%= @result %>

Week-4-Lab/calculatorApp/app/views/calculator/multiply.html.erb
<%= link_to 'Back to Full Calculator', calculate_path, class: "link-style" %>

<h1>Simple Calculator</h1>
<h3>Multiply</h3>

<%= form_with url: "/multiply", local: true, data: { turbo: false } do |f| %>
  <%= text_field_tag :number1 %>
  <%= text_field_tag :number2 %>
  <%= submit_tag "*" %>
<% end %>

<hr>

<h1>Multiply</h1>
<br>
<%= @num1 %> * <%= @num2 %> = <%= @result %>

Week-4-Lab/calculatorApp/app/views/calculator/subtract.html.erb
<%= link_to 'Back to Full Calculator', calculate_path, class: "link-style" %>

<h1>Simple Calculator</h1>
<h3>Subtract</h3>

<%= form_with url: "/subtract", local: true, data: { turbo: false } do |f| %>
  <%= text_field_tag :number1 %>
  <%= text_field_tag :number2 %>
  <%= submit_tag "-" %>
<% end %>

<hr>

<h1>Subtraction</h1>
<br>
<%= @num1 %> - <%= @num2 %> = <%= @result %>

Week-4-Lab/calculatorApp/app/views/calculator/sum.html.erb
<%= link_to 'Back to Full Calculator', calculate_path, class: "link-style" %>

<h1>Simple Calculator</h1>
<h3>Addition</h3>

<%= form_with url: "/sum", local: true, data: { turbo: false } do |f| %>
    <%= text_field_tag :number1 %>
    <%= text_field_tag :number2 %>
    <%= submit_tag "+" %>
<% end %>

<hr>

<h1>Sum</h1><br>

<%= @num1 %> + <%= @num2 %> = <%= @result %>

Week-4-Lab/calculatorApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalculatorApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>